AllCops:
  RunRailsCops: true
  Exclude:
    - test/dummy/db/schema.rb

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'

Metrics/ParameterLists:
  Exclude:
    - lib/tasks_scheduler/cron_parser_patch.rb
