---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - config/initializers/menus.rb
  - exe/tasks_scheduler
  - exe/tasks_scheduler_run_task
  - lib/tasks_scheduler/cron_parser_patch.rb
  - spec/code/rubocop_check_spec.rb
  - spec/models/scheduled_task_spec.rb
  - spec/spec_helper.rb
