#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'
require 'fileutils'

def find_rails_root(dir = Dir.pwd)
  fail 'Rails root not found' if dir == '' || dir == '/' || dir == '.'
  return dir if File.exist?(File.expand_path('config/environment.rb', dir))
  rails_root(File.dirname(dir))
end

rails_root = find_rails_root
dir = File.expand_path('tmp/pids', rails_root)
FileUtils.mkdir_p(dir)
Daemons.run_proc 'tasks_scheduler', dir_mode: :normal, dir: dir do
  require File.join(rails_root, 'config', 'environment')
  ::TasksScheduler::Checker.instance.run
end
